name: Needs review labeler

on:
  pull_request:
    branches: [main]
    
jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: add hold/needs-review label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: hold/needs-review
