name: Makefile CI

on:
  workflow_dispatch:

  push:

  pull_request:
    branches: [main]
    types: [labeled]

  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: ${{ github.event.label.name == 'lgtm' }}
    runs-on: ubuntu-22.04
    env:
      SHELL: /bin/bash

    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.10

      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
