name: Makefile CI

on:
  pull_request:
    branches: [main]
    types: [unlabeled]

jobs:
  build:
    if: ${{ github.event.label.name == 'hold/needs-review' }}
    runs-on: ubuntu-22.04
    env:
      SHELL: /bin/bash

    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.10

      - uses: actions/checkout@v3

      - name: Test command
        run: | 
          echo "Hello World!"

      - name: Re-label PR
        if: failure()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: hold/needs-review
